# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-13 18:41
from __future__ import unicode_literals

# import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20180614_0455'), ('blog', '0003_auto_20180618_1928'), ('blog', '0004_auto_20180620_0054'), ('blog', '0005_post_tags'), ('blog', '0006_auto_20180713_0250'), ('blog', '0007_auto_20180731_0417'), ('blog', '0008_auto_20190117_2127'), ('blog', '0009_auto_20190117_2140'), ('blog', '0010_highlightedcasestudy_highlighted_image'), ('blog', '0011_auto_20190117_2228'), ('blog', '0012_auto_20190713_1840')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                # ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('comment_amount', models.IntegerField(default=0)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('roles', models.CharField(max_length=500)),
                ('time_spent', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('client_type', models.CharField(max_length=100)),
                ('demonstrated_skills', models.CharField(max_length=500)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HighlightedCaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted_abstract', models.TextField(blank=True, default='')),
                ('leader_words', models.TextField(blank=True, default='')),
                ('leader_action', models.CharField(max_length=100)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CaseStudy')),
                ('is_public', models.BooleanField(default=False)),
                ('highlighted_image', models.URLField(blank=True, default='', max_length=500)),
                ('highlighted_image_css_position', models.CharField(blank=True, default='', max_length=10)),
                ('highlighted_image_css_position_mobile', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'ordering': ['-case_study__order', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('comment_amount', models.IntegerField(default=0)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('tags', models.CharField(blank=True, default='', max_length=200)),
                ('cover_image', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'abstract': False,
                'ordering': ['-order', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='casestudy',
            name='order',
            field=models.DecimalField(decimal_places=3, default=99, max_digits=5),
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-order', '-modified_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='client_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='demonstrated_skills',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='order',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='project_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='roles',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='time_spent',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='client_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='demonstrated_skills',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='project_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='roles',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='time_spent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-order', 'pk']},
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-order', '-pk']},
        ),
        migrations.AddField(
            model_name='casestudy',
            name='cover_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
