# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='order',
            field=models.DecimalField(decimal_places=3, default=99, max_digits=5),
        ),
        migrations.AddField(
            model_name='post',
            name='order',
            field=models.DecimalField(decimal_places=3, default=99, max_digits=5),
        ),
    ]
