# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180614_0455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-order', '-modified_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='highlightedcasestudy',
            options={'ordering': ['-case_study__order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-order', '-modified_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='client_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='demonstrated_skills',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='order',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='project_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='roles',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='time_spent',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='highlightedcasestudy',
            name='highlighted_abstract',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='highlightedcasestudy',
            name='leader_words',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='order',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
    ]
