# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180618_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='client_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='demonstrated_skills',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='project_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='roles',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='time_spent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='highlightedcasestudy',
            name='highlighted_abstract',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='highlightedcasestudy',
            name='leader_words',
            field=models.TextField(blank=True, default=''),
        ),
    ]
