# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-order', '-created_at']},
        ),
        migrations.AddField(
            model_name='highlightedcasestudy',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
