# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-31 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180713_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-order', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-order', 'pk']},
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
