# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180731_0417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestudy',
            options={'ordering': ['-order', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='highlightedcasestudy',
            options={'ordering': ['-case_study__order', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-order', '-pk']},
        ),
    ]
