# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190117_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='cover_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
