# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190117_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightedcasestudy',
            name='highlighted_image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
