# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_highlightedcasestudy_highlighted_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightedcasestudy',
            name='highlighted_image_css_position',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='highlightedcasestudy',
            name='highlighted_image_css_position_mobile',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
